// Supabase database schema definitions
// These should match your Supabase table definitions

export const tables = {
  users: {
    id: 'uuid primary key default gen_random_uuid()',
    email: 'text unique not null',
    created_at: 'timestamp with time zone default now()',
    updated_at: 'timestamp with time zone default now()',
  },
  workspaces: {
    id: 'uuid primary key default gen_random_uuid()',
    user_id: 'uuid references users(id) not null',
    name: 'text not null',
    description: 'text',
    created_at: 'timestamp with time zone default now()',
    updated_at: 'timestamp with time zone default now()',
  },
  boards: {
    id: 'uuid primary key default gen_random_uuid()',
    workspace_id: 'uuid references workspaces(id) not null',
    name: 'text not null',
    description: 'text',
    created_at: 'timestamp with time zone default now()',
    updated_at: 'timestamp with time zone default now()',
  },
  lists: {
    id: 'uuid primary key default gen_random_uuid()',
    board_id: 'uuid references boards(id) not null',
    name: 'text not null',
    position: 'integer not null',
    wip_limit: 'integer',
    created_at: 'timestamp with time zone default now()',
    updated_at: 'timestamp with time zone default now()',
  },
  cards: {
    id: 'uuid primary key default gen_random_uuid()',
    board_id: 'uuid references boards(id) not null',
    list_id: 'uuid references lists(id) not null',
    title: 'text not null',
    description: 'text',
    position: 'integer not null',
    due_date: 'timestamp with time zone',
    due_date_reminder: 'boolean default false',
    priority: 'text check (priority in (\'high\', \'medium\', \'low\'))',
    labels: 'jsonb',
    assignees: 'jsonb',
    estimated_hours: 'numeric',
    actual_hours: 'numeric',
    checklist: 'jsonb',
    attachments: 'jsonb',
    color: 'text',
    column_status: 'text check (column_status in (\'todo\', \'in-progress\', \'review\', \'done\'))',
    created_at: 'timestamp with time zone default now()',
    updated_at: 'timestamp with time zone default now()',
  },
  card_comments: {
    id: 'uuid primary key default gen_random_uuid()',
    card_id: 'uuid references cards(id) not null',
    user_id: 'uuid references users(id) not null',
    content: 'text not null',
    created_at: 'timestamp with time zone default now()',
    updated_at: 'timestamp with time zone default now()',
  },
  card_activity_log: {
    id: 'uuid primary key default gen_random_uuid()',
    card_id: 'uuid references cards(id) not null',
    user_id: 'uuid references users(id) not null',
    action: 'text not null',
    changes: 'jsonb',
    created_at: 'timestamp with time zone default now()',
  },
  behavior_profiles: {
    id: 'uuid primary key default gen_random_uuid()',
    user_id: 'uuid references users(id) not null',
    goals: 'jsonb',
    values: 'jsonb',
    anchor_routines: 'jsonb',
    preferred_tone: 'text check (preferred_tone in (\'coach\', \'direct\', \'formal\'))',
    nudge_frequency: 'text check (nudge_frequency in (\'daily\', \'weekly\', \'biweekly\'))',
    created_at: 'timestamp with time zone default now()',
    updated_at: 'timestamp with time zone default now()',
  },
}
